[package]
name = "nes-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
sdl2 = { version = "0.37.0", optional = true }

[[bin]]
name = "rom-test-snake"
required-features = ["sdl2"]

[[bin]]
name = "cpu-test-snake"
required-features = ["sdl2"]
